language: python

services:
  - docker

python:
- 3.4
- 3.4
- 3.5
- 3.6

matrix:
  include:
    - os: linux

    - os: osx
      sudo: required
      language: generic
      before_install:
        - brew update
        - brew install python3
        - pip install pathlib

install:
  - pip install .

script:
  - pip install pytest-cov codecov
  - pip install --upgrade setuptools
  - py.test --cov=./ ./
  - cd test/simple_app && vagga _build test_simple_flask

after_success:
  - codecov
