language: python

services:
  - docker

python:
- 3.4
- 3.4
- 3.5
- 3.6

matrix:
  include:
    - os: linux
      before_install:
        - pip install pytest-cov codecov

    - os: osx
      sudo: required
      language: generic
      before_install:
        - brew update
        - brew install python3
        - pip install pytest-cov codecov
        - pip install pathlib

  install:
    - pip install .

  script:
    - py.test --cov=./ ./
    - cd test/simple_app && vagga run

  after_success:
    - codecov

