language: python

python:
- 3.4.2
- 3.4.3
- 3.5.2
- 3.5
- 3.6

services:
  - docker

matrix:
  include:
    - os: linux
    - os: osx

before_install:
  - pip install pytest-cov codecov

install:
  - pip install .

script:
  - py.test --cov=./ ./
  - cd test/simple_app && vagga run
  - curl http://0.0.0.0:5000

after_success:
  - codecov
