language: python
python:
- "3.4"
install: "pip install ."

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
script: |
    if [[ $TRAVIS_OS_NAME != osx ]]; then
        vagga
    fi

