language: python

services:
  - docker

python:
- 3.6
- 3.5
- 3.4

matrix:
  include:
    - os: linux

    - os: osx
      sudo: required
      language: generic
      before_install:
        - brew update
        - brew install python3
        - virtualenv venv -p python3
        - source venv/bin/activate

before_script:
  - |
     export PATH=$HOME/.cargo/bin:$PATH:$PATH &&
     cargo install --force travis-after-all

install:
  - pip install .

script:
  - pip install pytest-cov codecov
  - py.test --cov=./ ./
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then cd test/simple_app && vagga _build test_simple_flask ; fi

after_success:
  - travis-after-all && codecov
