language: python
python:
- "3.4"
services: [docker]
install:
- pip install .

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
script: |
    if [[ $TRAVIS_OS_NAME != osx ]]; then
        cd example
        test "$(vagga py)" = "Python 3.5.1"
    fi

